import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US':{
      'welcome': 'Welcome back',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_out': 'Sign Out',
      'forgot': 'Forgot password ?',
      'forgot_pass': 'Forgot password',
      'remember_pass': 'Remember your password ?',
      'fb_sign': 'Sign in with Facebook',
      'fb_signup': "Sign up with Facebook",
      'or': 'or',
      'dont_have_account': "Don't have an account ?",
      'have_account': "Have an account ?",
      "lbl_phone_number":"Phone number",
      "lbl_oldpassword":"Current Password",
      "lbl_password":"Password",
      "lbl_cpassword":"Confirm your password",
      "lbl_email":"Email",
      "lbl_name":"Name",
      "link_click_here":'Click here',
      "txt_loading":"Loading...",
      "txt_get_starting":"Getting Started",
      "lbl_send":'Send code',
      "txt_choose_p":"Choose pictures",
      "txt_create_m":"Create new model",
      "txt_my_pictures":"My Pictures",
      "txt_pictures":"Pictures",
      "txt_account":"Account",
      "txt_my_balance":"My subscription",
      "txt_edit_prof": "Edit profile",
      "txt_change_pass": "Changer password",
      "txt_change_lang": "Changer language",
      "txt_fr": "French",
      "txt_en": "English",
      "txt_lang_title": "Change language",
    },
    'fr_FR':{
      'welcome': 'Bienvenue',
      'sign_in': 'Se connecter',
      'sign_up': "S'inscrire",
      'sign_out': "Se déconnecter",
      'forgot': "Mot de passe oublié ?",
      'forgot_pass': 'Mot de passe oublié',
      'remember_pass': 'Tu te souviens de ton mot de passe ?',
      'fb_sign': "Connectez-vous avec Facebook",
      'fb_signup': "S'inscrire avec Facebook",
      'or': 'ou',
      'dont_have_account': "Vous n'avez pas de compte ?",
      'have_account': "vous avez un compte ?",
      "lbl_phone_number":"Téléphone",
      "lbl_oldpassword":"Mot de passe actuelle",
      "lbl_password":"Mot de passe",
      "lbl_cpassword":"Confirmer votre mot de passe",
      "lbl_email":"Email",
      "lbl_name":"Nom",
      "link_click_here":'Cliquez ici',
      "txt_loading":"Chargement...",
      "txt_male":"Homme",
      "txt_female":"Femme",
      "txt_get_starting":"Commencer",
      "lbl_send":'Envoyer le code',
      "txt_choose_p":"Choisissez des photos",
      "txt_create_m":"Créer nouveau modèle",
      "txt_my_pictures":"Mes photos",
      "txt_pictures":"Photos",
      "txt_account":"Compte",
      "txt_my_balance":"Mon abonnement",
      "txt_edit_prof": "Modifier le profil",
      "txt_change_pass": "Changer mot de passe",
      "txt_change_lang": "Changer la langue",
      "txt_fr": "Français",
      "txt_en": "Anglais",
      "txt_lang_title": "Changer la langue",
    },
  };

}